config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root to: 'products#index'
  resources :products do
    resources :reviews
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :usa, -> { ( where(country_of_origin: "United States").limit(3)) }
  scope :most_reviews, -> {(
      select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
      .joins(:reviews)
      .group("products.id")
      .order("reviews_count DESC")
      .limit(3)
      )}

  before_save(:titleize_product)

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates_length_of :content_body, minimum: 50
  validates_length_of :content_body, maximum: 250

  before_save(:titleize_author)

  private
    def titleize_author
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :authenticate_user!, :except => [:show, :index]

  def index
    @products = Product.all
    @recent_products = Product.three_most_recent
    @most_reviewed_products = Product.most_reviews
    @usa_products = Product.usa
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :authenticate_user!, :except => [:show, :index]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    @product = Product.find(params[:product_id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_product_errors.html.erb
<% if @product.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/product_errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :cost %><br>
  <%= f.text_field :cost %><br>
  <%= f.label :country_of_origin %><br>
  <%= f.text_field :country_of_origin %><br>
  <%= f.submit  %>
<% end %>

app/views/layouts/_review_errors.html.erb
<% if @review.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/review_errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %><br>
  <%= f.text_field :author %><br>
  <%= f.label :rating %><br>
  <%= f.text_field :rating %><br>
  <%= f.label :content_body %><br>
  <%= f.text_area :content_body %><br>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen|Righteous&display=swap' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <% if current_user %>
     <%= current_user.email %> | <%= link_to "Sign out", '/users/sign_out', method: :delete %>
     <% else %>
     <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
     <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h3>Most Recent</h3>
      </div>
      <div class="card-body">
        <% if @recent_products.any? %>
          <% @recent_products.each do |product| %>
          <div class="card">
            <div class="card-body">
              <%= link_to product.name, product_path(product) %>
            </div>
          </div>
          <% end %>
        <% else %>
        <p>There are no products yet.</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h3>Most Reviewed</h3>
      </div>
      <div class="card-body">
        <% if @most_reviewed_products.any? %>
          <% @most_reviewed_products.each do |product| %>
          <div class="card">
            <div class="card-body">
              <%= link_to product.name, product_path(product) %>
            </div>
          </div>
          <% end %>
        <% else %>
        <p>There are no products yet.</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h3>Made in the USA</h3>
      </div>
      <div class="card-body">
        <% if @usa_products.any? %>
          <% @usa_products.each do |product| %>
          <div class="card">
            <div class="card-body">
              <%= link_to product.name, product_path(product) %>
            </div>
          </div>
          <% end %>
        <% else %>
        <p>There are no USA products yet.</p>
        <% end %>
      </div>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3>All Products</h3>
      </div>
      <div class="row">
        <% if @products.any? %>
        <% @products.each do |product| %>
        <div class="col-md-3">
          <div class="card-body">
            <div class="card">
              <div class="card-body">
                <%= link_to product.name, product_path(product) %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <% else %>
        <p>There are no products yet.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<p><%= link_to "Create new product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>$<%= @product.cost %></h3>
<h3><%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<div class="card">
  <div class="card-header">
    <h1><%= @product.name %></h1>
  </div>
  <div class="card-body">
    <h3><%= @review.author %></h3>
    <p><%= @review.content_body %></p>
    <p><%= @review.rating %>/5 Stars</p>
  </div>
</div>

<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>